name: GitHub Actions CI 

on:
  push:
    branches:
      - main
  pull_request:

env:
  PGDATABASE: test
  PGPASSWORD: postgres
  PGUSER: postgres
  PGHOST: localhost
  PGPORT: 5432

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: rabbitmq:3.11.13
        ports:
          - 15672:15672
          - 5672:5672

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip==24.0
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        python -m nltk.downloader punkt
        python -m nltk.downloader stopwords
        python -m nltk.downloader wordnet
        python -m nltk.downloader omw-1.4        
    - name: Test with pytest
      run: |
        pytest --cov=adsplanetnamepipe --cov-report=xml
    - name: Upload coverage data to coveralls.io
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
